### ISSUE TITLE
Change it!

### ISSUE THREAD

**Issue by 5290charlie** [brandoncabael/testnode#1]
Make a subtle change to `index.js` and then publish a new patch version to npm

1. Add & commit changes to git
  - `git add`, `git commit`, etc
2. Increase the package patch number `1.0.X`
  - `npm version patch`
3. Push new versioned tag to GitHub
  - `git push origin --tags`
4. Publish to `npm`
  - `npm publish` (remember, you'll need to re-authenticate with npm using `npm login`)

**Comment by brandoncabael** [comment]
It has been changed
